exports.dateToString = function (date){
    return date.toISOString().substring(0,10);
};

exports.name2Code = {
    "United Arab Emirates Dirham": "AED", 
    "Afghan Afghani": "AFN", 
    "Albanian Lek": "ALL", 
    "Armenian Dram": "AMD", 
    "Netherlands Antillean Guilder": "ANG", 
    "Angolan Kwanza": "AOA", 
    "Argentine Peso": "ARS", 
    "Australian Dollar": "AUD", 
    "Aruban Florin": "AWG", 
    "Azerbaijani Manat": "AZN", 
    "Bosnia-Herzegovina Convertible Mark": "BAM", 
    "Barbadian Dollar": "BBD", 
    "Bangladeshi Taka": "BDT", 
    "Bulgarian Lev": "BGN", 
    "Bahraini Dinar": "BHD", 
    "Burundian Franc": "BIF", 
    "Bermudan Dollar": "BMD", 
    "Brunei Dollar": "BND", 
    "Bolivian Boliviano": "BOB", 
    "Brazilian Real": "BRL", 
    "Bahamian Dollar": "BSD", 
    "Bitcoin": "BTC", 
    "Bhutanese Ngultrum": "BTN", 
    "Botswanan Pula": "BWP", 
    "Belarusian Ruble": "BYN", 
    "Belize Dollar": "BZD", 
    "Canadian Dollar": "CAD", 
    "Congolese Franc": "CDF", 
    "Swiss Franc": "CHF", 
    "Chilean Unit of Account (UF)": "CLF", 
    "Chilean Peso": "CLP", 
    "Chinese Yuan (Offshore)": "CNH", 
    "Chinese Yuan": "CNY", 
    "Colombian Peso": "COP", 
    "Costa Rican Colón": "CRC", 
    "Cuban Convertible Peso": "CUC", 
    "Cuban Peso": "CUP", 
    "Cape Verdean Escudo": "CVE", 
    "Czech Republic Koruna": "CZK", 
    "Djiboutian Franc": "DJF", 
    "Danish Krone": "DKK", 
    "Dominican Peso": "DOP", 
    "Algerian Dinar": "DZD", 
    "Egyptian Pound": "EGP", 
    "Eritrean Nakfa": "ERN", 
    "Ethiopian Birr": "ETB", 
    "Euro": "EUR", 
    "Fijian Dollar": "FJD", 
    "Falkland Islands Pound": "FKP", 
    "British Pound Sterling": "GBP", 
    "Georgian Lari": "GEL", 
    "Guernsey Pound": "GGP", 
    "Ghanaian Cedi": "GHS", 
    "Gibraltar Pound": "GIP", 
    "Gambian Dalasi": "GMD", 
    "Guinean Franc": "GNF", 
    "Guatemalan Quetzal": "GTQ", 
    "Guyanaese Dollar": "GYD", 
    "Hong Kong Dollar": "HKD", 
    "Honduran Lempira": "HNL", 
    "Croatian Kuna": "HRK", 
    "Haitian Gourde": "HTG", 
    "Hungarian Forint": "HUF", 
    "Indonesian Rupiah": "IDR", 
    "Israeli New Sheqel": "ILS", 
    "Manx pound": "IMP", 
    "Indian Rupee": "INR", 
    "Iraqi Dinar": "IQD", 
    "Iranian Rial": "IRR", 
    "Icelandic Króna": "ISK", 
    "Jersey Pound": "JEP", 
    "Jamaican Dollar": "JMD", 
    "Jordanian Dinar": "JOD", 
    "Japanese Yen": "JPY", 
    "Kenyan Shilling": "KES", 
    "Kyrgystani Som": "KGS", 
    "Cambodian Riel": "KHR", 
    "Comorian Franc": "KMF", 
    "North Korean Won": "KPW", 
    "South Korean Won": "KRW", 
    "Kuwaiti Dinar": "KWD", 
    "Cayman Islands Dollar": "KYD", 
    "Kazakhstani Tenge": "KZT", 
    "Laotian Kip": "LAK", 
    "Lebanese Pound": "LBP", 
    "Sri Lankan Rupee": "LKR", 
    "Liberian Dollar": "LRD", 
    "Lesotho Loti": "LSL", 
    "Libyan Dinar": "LYD", 
    "Moroccan Dirham": "MAD", 
    "Moldovan Leu": "MDL", 
    "Malagasy Ariary": "MGA", 
    "Macedonian Denar": "MKD", 
    "Myanma Kyat": "MMK", 
    "Mongolian Tugrik": "MNT", 
    "Macanese Pataca": "MOP", 
    "Mauritanian Ouguiya (pre-2018)": "MRO", 
    "Mauritanian Ouguiya": "MRU", 
    "Mauritian Rupee": "MUR", 
    "Maldivian Rufiyaa": "MVR", 
    "Malawian Kwacha": "MWK", 
    "Mexican Peso": "MXN", 
    "Malaysian Ringgit": "MYR", 
    "Mozambican Metical": "MZN", 
    "Namibian Dollar": "NAD", 
    "Nigerian Naira": "NGN", 
    "Nicaraguan Córdoba": "NIO", 
    "Norwegian Krone": "NOK", 
    "Nepalese Rupee": "NPR", 
    "New Zealand Dollar": "NZD", 
    "Omani Rial": "OMR", 
    "Panamanian Balboa": "PAB", 
    "Peruvian Nuevo Sol": "PEN", 
    "Papua New Guinean Kina": "PGK", 
    "Philippine Peso": "PHP", 
    "Pakistani Rupee": "PKR", 
    "Polish Zloty": "PLN", 
    "Paraguayan Guarani": "PYG", 
    "Qatari Rial": "QAR", 
    "Romanian Leu": "RON", 
    "Serbian Dinar": "RSD", 
    "Russian Ruble": "RUB", 
    "Rwandan Franc": "RWF", 
    "Saudi Riyal": "SAR", 
    "Solomon Islands Dollar": "SBD", 
    "Seychellois Rupee": "SCR", 
    "Sudanese Pound": "SDG", 
    "Swedish Krona": "SEK", 
    "Singapore Dollar": "SGD", 
    "Saint Helena Pound": "SHP", 
    "Sierra Leonean Leone": "SLL", 
    "Somali Shilling": "SOS", 
    "Surinamese Dollar": "SRD", 
    "South Sudanese Pound": "SSP", 
    "São Tomé and Príncipe Dobra (pre-2018)": "STD",
    "São Tomé and Príncipe Dobra": "STN", 
    "Salvadoran Colón": "SVC", 
    "Syrian Pound": "SYP", 
    "Swazi Lilangeni": "SZL", 
    "Thai Baht": "THB", 
    "Tajikistani Somoni": "TJS", 
    "Turkmenistani Manat": "TMT", 
    "Tunisian Dinar": "TND", 
    "Tongan Pa'anga": "TOP", 
    "Turkish Lira": "TRY", 
    "Trinidad and Tobago Dollar": "TTD", 
    "New Taiwan Dollar": "TWD", 
    "Tanzanian Shilling": "TZS", 
    "Ukrainian Hryvnia": "UAH", 
    "Ugandan Shilling": "UGX", 
    "United States Dollar": "USD", 
    "Uruguayan Peso": "UYU", 
    "Uzbekistan Som": "UZS", 
    "Venezuelan Bolívar Fuerte": "VEF", 
    "Vietnamese Dong": "VND", 
    "Vanuatu Vatu": "VUV", 
    "Samoan Tala": "WST", 
    "CFA Franc BEAC": "XAF", 
    "Silver Ounce": "XAG", 
    "Gold Ounce": "XAU", 
    "East Caribbean Dollar": "XCD", 
    "Special Drawing Rights": "XDR", 
    "CFA Franc BCEAO": "XOF", 
    "Palladium Ounce": "XPD", 
    "CFP Franc": "XPF", 
    "Platinum Ounce": "XPT", 
    "Yemeni Rial": "YER", 
    "South African Rand": "ZAR", 
    "Zambian Kwacha": "ZMW", 
    "Zimbabwean Dollar": "ZWL"
 };

 exports.code2Name = {
    "AED": "United Arab Emirates Dirham",
    "AFN": "Afghan Afghani",
    "ALL": "Albanian Lek",
    "AMD": "Armenian Dram",
    "ANG": "Netherlands Antillean Guilder",
    "AOA": "Angolan Kwanza",
    "ARS": "Argentine Peso",
    "AUD": "Australian Dollar",
    "AWG": "Aruban Florin",
    "AZN": "Azerbaijani Manat",
    "BAM": "Bosnia-Herzegovina Convertible Mark",
    "BBD": "Barbadian Dollar",
    "BDT": "Bangladeshi Taka",
    "BGN": "Bulgarian Lev",
    "BHD": "Bahraini Dinar",
    "BIF": "Burundian Franc",
    "BMD": "Bermudan Dollar",
    "BND": "Brunei Dollar",
    "BOB": "Bolivian Boliviano",
    "BRL": "Brazilian Real",
    "BSD": "Bahamian Dollar",
    "BTC": "Bitcoin",
    "BTN": "Bhutanese Ngultrum",
    "BWP": "Botswanan Pula",
    "BYN": "Belarusian Ruble",
    "BZD": "Belize Dollar",
    "CAD": "Canadian Dollar",
    "CDF": "Congolese Franc",
    "CHF": "Swiss Franc",
    "CLF": "Chilean Unit of Account (UF)",
    "CLP": "Chilean Peso",
    "CNH": "Chinese Yuan (Offshore)",
    "CNY": "Chinese Yuan",
    "COP": "Colombian Peso",
    "CRC": "Costa Rican Colón",
    "CUC": "Cuban Convertible Peso",
    "CUP": "Cuban Peso",
    "CVE": "Cape Verdean Escudo",
    "CZK": "Czech Republic Koruna",
    "DJF": "Djiboutian Franc",
    "DKK": "Danish Krone",
    "DOP": "Dominican Peso",
    "DZD": "Algerian Dinar",
    "EGP": "Egyptian Pound",
    "ERN": "Eritrean Nakfa",
    "ETB": "Ethiopian Birr",
    "EUR": "Euro",
    "FJD": "Fijian Dollar",
    "FKP": "Falkland Islands Pound",
    "GBP": "British Pound Sterling",
    "GEL": "Georgian Lari",
    "GGP": "Guernsey Pound",
    "GHS": "Ghanaian Cedi",
    "GIP": "Gibraltar Pound",
    "GMD": "Gambian Dalasi",
    "GNF": "Guinean Franc",
    "GTQ": "Guatemalan Quetzal",
    "GYD": "Guyanaese Dollar",
    "HKD": "Hong Kong Dollar",
    "HNL": "Honduran Lempira",
    "HRK": "Croatian Kuna",
    "HTG": "Haitian Gourde",
    "HUF": "Hungarian Forint",
    "IDR": "Indonesian Rupiah",
    "ILS": "Israeli New Sheqel",
    "IMP": "Manx pound",
    "INR": "Indian Rupee",
    "IQD": "Iraqi Dinar",
    "IRR": "Iranian Rial",
    "ISK": "Icelandic Króna",
    "JEP": "Jersey Pound",
    "JMD": "Jamaican Dollar",
    "JOD": "Jordanian Dinar",
    "JPY": "Japanese Yen",
    "KES": "Kenyan Shilling",
    "KGS": "Kyrgystani Som",
    "KHR": "Cambodian Riel",
    "KMF": "Comorian Franc",
    "KPW": "North Korean Won",
    "KRW": "South Korean Won",
    "KWD": "Kuwaiti Dinar",
    "KYD": "Cayman Islands Dollar",
    "KZT": "Kazakhstani Tenge",
    "LAK": "Laotian Kip",
    "LBP": "Lebanese Pound",
    "LKR": "Sri Lankan Rupee",
    "LRD": "Liberian Dollar",
    "LSL": "Lesotho Loti",
    "LYD": "Libyan Dinar",
    "MAD": "Moroccan Dirham",
    "MDL": "Moldovan Leu",
    "MGA": "Malagasy Ariary",
    "MKD": "Macedonian Denar",
    "MMK": "Myanma Kyat",
    "MNT": "Mongolian Tugrik",
    "MOP": "Macanese Pataca",
    "MRO": "Mauritanian Ouguiya (pre-2018)",
    "MRU": "Mauritanian Ouguiya",
    "MUR": "Mauritian Rupee",
    "MVR": "Maldivian Rufiyaa",
    "MWK": "Malawian Kwacha",
    "MXN": "Mexican Peso",
    "MYR": "Malaysian Ringgit",
    "MZN": "Mozambican Metical",
    "NAD": "Namibian Dollar",
    "NGN": "Nigerian Naira",
    "NIO": "Nicaraguan Córdoba",
    "NOK": "Norwegian Krone",
    "NPR": "Nepalese Rupee",
    "NZD": "New Zealand Dollar",
    "OMR": "Omani Rial",
    "PAB": "Panamanian Balboa",
    "PEN": "Peruvian Nuevo Sol",
    "PGK": "Papua New Guinean Kina",
    "PHP": "Philippine Peso",
    "PKR": "Pakistani Rupee",
    "PLN": "Polish Zloty",
    "PYG": "Paraguayan Guarani",
    "QAR": "Qatari Rial",
    "RON": "Romanian Leu",
    "RSD": "Serbian Dinar",
    "RUB": "Russian Ruble",
    "RWF": "Rwandan Franc",
    "SAR": "Saudi Riyal",
    "SBD": "Solomon Islands Dollar",
    "SCR": "Seychellois Rupee",
    "SDG": "Sudanese Pound",
    "SEK": "Swedish Krona",
    "SGD": "Singapore Dollar",
    "SHP": "Saint Helena Pound",
    "SLL": "Sierra Leonean Leone",
    "SOS": "Somali Shilling",
    "SRD": "Surinamese Dollar",
    "SSP": "South Sudanese Pound",
    "STD": "São Tomé and Príncipe Dobra (pre-2018)",
    "STN": "São Tomé and Príncipe Dobra",
    "SVC": "Salvadoran Colón",
    "SYP": "Syrian Pound",
    "SZL": "Swazi Lilangeni",
    "THB": "Thai Baht",
    "TJS": "Tajikistani Somoni",
    "TMT": "Turkmenistani Manat",
    "TND": "Tunisian Dinar",
    "TOP": "Tongan Pa'anga",
    "TRY": "Turkish Lira",
    "TTD": "Trinidad and Tobago Dollar",
    "TWD": "New Taiwan Dollar",
    "TZS": "Tanzanian Shilling",
    "UAH": "Ukrainian Hryvnia",
    "UGX": "Ugandan Shilling",
    "USD": "United States Dollar",
    "UYU": "Uruguayan Peso",
    "UZS": "Uzbekistan Som",
    "VEF": "Venezuelan Bolívar Fuerte",
    "VND": "Vietnamese Dong",
    "VUV": "Vanuatu Vatu",
    "WST": "Samoan Tala",
    "XAF": "CFA Franc BEAC",
    "XAG": "Silver Ounce",
    "XAU": "Gold Ounce",
    "XCD": "East Caribbean Dollar",
    "XDR": "Special Drawing Rights",
    "XOF": "CFA Franc BCEAO",
    "XPD": "Palladium Ounce",
    "XPF": "CFP Franc",
    "XPT": "Platinum Ounce",
    "YER": "Yemeni Rial",
    "ZAR": "South African Rand",
    "ZMW": "Zambian Kwacha",
    "ZWL": "Zimbabwean Dollar"
};

exports.dateValidation = function (date){
    if(!String(date).match(/([0-9][0-9][0-9][0-9])-([0-1][0-9])-([0-3][0-9])/)){
        return false;
    }
    else{
        if(new Date(date+"T00:00:00") == "Invalid Date"){
            return false;
        }
        else{
            return true;
        }
    }
};

exports.isNumericString = function (numericString){
    return (String(numericString).match(/[0-9]+(\.[0-9]+)?/));
};